### ISSUE TITLE
[discussion] should `value` be optional for `format()` and `formatToPart()`?

### ISSUE THREAD

**Issue by caridy** [caridy/proposal-intl-relative-time#19]
In other formatters the value is always optional...

**Comment by rxaviers** [comment]
Good point.
- new Intl.NumberFormat().format() // 'NaN' for English.
- new Intl.DateTimeFormat().format() // '3/21/2017' (i.e., today) for English.

**Comment by rxaviers** [comment]
Any suggestions? If `value` is optional, we may need a default `unit` for #18.

**Comment by zbraniecki** [comment]
My reviewer said "I suggest this would be better as just throwing."

I don't like the fact that we silently accept undefined, but I can see how the defaults make sense somehow.
For RelativeTimeFormat, I'd say we should throw.

Alternatively we could format `now`, but since we want to require second parameter, then there's no value in allowing the first one to be optional.

**Comment by littledan** [comment]
Now that we require a type argument, with no `bestFit` default,  throwing falls out naturally, since `"undefined"` is not among the accepted types, right?

**Comment by caridy** [comment]
Since `value` and `unit` are now required (PR #25), we not longer rely on `now` so this becomes irrelevant.
